version: '3.7'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    build:
      context: ../
      dockerfile: api_yamdb/Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    ports:
     - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
